markdown: rdiscount
appname: Carnac
appslogan: ', the Magnificent Keyboard Utility'
username: Code52
reponame: carnac
accent: 7100B3
darkaccent: 7100B3
description: A WPF Markdown editor inspired by <a href="https://bitbucket.org/wcoenen/downmarker">Downmarker</a>. Read the original brief on <a href="http://code52.org">Code52</a>
downloadurl: https://github.com/downloads/Code52/carnac/Carnac.zip

#feature1title: 'Side-by-side Preview'
#feature2title: 'Single exe, portable'
#feature3title: 'Spellchecker'

#feature1desc: 'Markdown is easy to grok, but how do you know its going to turn out perfect? A side-by-side preview, rendered in real time, thats how!'
#feature2desc: 'Portable, right out of the box. Everything is in a single executable.'
#feature3desc: 'Markdown can be done in any text editor, but why must the experience degrade to Notepad? No more. MarkPad has spellchecker and a floating syntax tool bar'